version: '3.9'
services:
  cami_uhr:
    container_name: cami_uhr
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "28554:3000"
    networks:
      projects:
        ipv4_address: 192.169.3.1
    restart: unless-stopped


networks:
  projects:
    external: true