version: '3.9'
services:
  backend:
    container_name: prayer_times_hadith_and_annocunment_backend
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./logs:/code/logs/
    ports:
      - "12825:80"
    networks:
      projects:
        ipv4_address: 192.169.3.2
      intern:
    restart: unless-stopped


  frontend:
    container_name: prayer_times_hadith_and_annocunment_frontend
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "31428:3000"
    networks:
      projects:
        ipv4_address: 192.169.3.3
    restart: unless-stopped



networks:
  projects:
    external: true
  intern:
    external: true