version: '3.9'
services:
  backend:
    container_name: prayer_times_hadith_and_annocunment_backend
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    ports:
      - "12825:80"
    restart: unless-stopped
    networks:
      - intern
    user: "1002:1002"  # Add this to set permissions based on the host user


  frontend:
    container_name: prayer_times_hadith_and_annocunment_frontend
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "31428:3000"
    restart: unless-stopped
    networks:
      - intern



networks:
  intern:
    external: true